name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and push Docker image
      run: |
        az acr login --name kanchantestregistry
        docker build . -t <ACR_NAME>.azurecr.io/myapp:${{ github.sha }}
        docker push <ACR_NAME>.azurecr.io/myapp:${{ github.sha }}
